### ISSUE TITLE
Missing Rule Details

### ISSUE THREAD

**Issue by kingthorin** [SasanLabs/owasp-zap-fileupload-addon#17]
**Describe the bug**
As reported [here](https://github.com/zaproxy/zaproxy/issues/7228), the File Upload scan rule has no name for display in the policy manager and progress dialog.

**To Reproduce**
- Start an Active Scan
- Click on the Progress icon 
-- ![image](https://user-images.githubusercontent.com/10052587/164455219-88058065-f8a2-4b80-a347-1931defc7f7e.png)
- scroll to the bottom of the window listing the attacks
- observe an attack missing a title between CORS Header and Spring Actuator Information Leak

**Expected behavior**
Expect for all attacks to have a title so one knows what attack vector is used. Also for debugging if something goes wrong with this specific attack.

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/164451919-ff1cacdc-7005-44ce-9b94-a4e436363267.png)

and

![image](https://user-images.githubusercontent.com/10052587/164456157-84e79186-826e-407b-9061-7b6858378d17.png)

**Desktop (please complete the following information):**
[id=fileupload, version=1.1.0],

**Additional context**
Can also be reproduced with:  https://github.com/zaproxy/community-scripts/blob/main/standalone/Active%20scan%20rule%20list.js

**Comment by kingthorin** [comment]
This also seems to happen on subsequent starts of ZAP (even when the extension is enabled). Moving the i18n init to a static block seems to address the issue.

**Comment by kingthorin** [comment]
> I just need you to confirm that the Scan Rule with work properly with the extension disabled. It seems like the extension is only responsible for hooking the options/params, so as long as they default appropriately it should be fine.

Poke @preetkaran20 :grinning:

**Comment by preetkaran20** [comment]
Sorry for the late reply, I was confused and later forget about it. Are we not facing the same issue in jwt add-on? Then we can initialize in init function similar to jwt add-on https://github.com/SasanLabs/owasp-zap-jwt-addon/blob/master/src/main/java/org/zaproxy/zap/extension/jwt/JWTExtension.java#L65

**Comment by preetkaran20** [comment]
I am not sure how we can disable extension and what is the impact of that. Will it not call the hook method? If so, Then the option params will not get injected and scanrule will not execute any attack and just returns.

**Comment by kingthorin** [comment]
Yes it probably impacts the JWT add-on as well. (I can PR it too, if it'll work without the extension.) I didn't check it specifically. But I think thc202 mentioned the same.

If the extension is disabled then no the hook method won't be called.

Okay that's fine then, I'll PR the change putting the i18n init in a static block.

**Comment by preetkaran20** [comment]
I will tests the add-on from my side as well.
