### ISSUE TITLE
Skip Scan Rule when configuration missing

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/owasp-zap-fileupload-addon#8]
**Describe the bug**
Currently, we skip the scan rule if any of the configurations for file upload are not set. But we are not indicating the reason for skipping the scan rule. Look at: https://github.com/SasanLabs/owasp-zap-fileupload-addon/pull/7#discussion_r692341701 for more information.

**Comment by thc202** [comment]
The rule is not being skipped yet, it's running for all messages (just not attacking them).

**Comment by preetkaran20** [comment]
oh ok, but that should not be an issue as it is not firing any extra requests.

**Comment by thc202** [comment]
It's an issue in that it still does unnecessary work (e.g. checking/parsing all messages).

**Comment by preetkaran20** [comment]
oh ok sure. 

thanks

**Comment by preetkaran20** [comment]
Following PR https://github.com/SasanLabs/owasp-zap-fileupload-addon/pull/10 will address this issue.

**Comment by preetkaran20** [comment]
handled in https://github.com/SasanLabs/owasp-zap-fileupload-addon/releases/tag/1.1.0
